function [stoptorque,goal_current,current,velocity1,position,Fx1,Fy,Fz1,Mx,My,Mz,counterclock,Time1] = importTxtData3(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [STOPTORQUE,GOAL_CURRENT,CURRENT,VELOCITY1,POSITION,FX1,FY,FZ1,MX,MY,MZ,COUNTERCLOCK,TIME1]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [STOPTORQUE,GOAL_CURRENT,CURRENT,VELOCITY1,POSITION,FX1,FY,FZ1,MX,MY,MZ,COUNTERCLOCK,TIME1]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [stoptorque,goal_current,current,velocity1,position,Fx1,Fy,Fz1,Mx,My,Mz,counterclock,Time1] = importfile('20.txt',2, 538);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/08/30 16:03:32

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
stoptorque = dataArray{:, 1};
goal_current = dataArray{:, 2};
current = dataArray{:, 3};
velocity1 = dataArray{:, 4};
position = dataArray{:, 5};
Fx1 = dataArray{:, 6};
Fy = dataArray{:, 7};
Fz1 = dataArray{:, 8};
Mx = dataArray{:, 9};
My = dataArray{:, 10};
Mz = dataArray{:, 11};
counterclock = dataArray{:, 12};
Time1 = dataArray{:, 13};


